

const answers = {
    positive: [
        "The stars are cheering for you!",
        "Absolutely, with glitter on top.",
        "The universe high-fived you.",
        "The answer sparkles with 'yes.'",
        "The tea leaves spelled 'heck yeah!'",
        "The cosmic winds are in your favor.",
        "The oracle did a happy dance.",
        "The runes gleam with approval.",
        "The pendulum swung to 'heck yes!'",
        "The crystal ball is doing fireworks.",
        "Fate just winked at you.",
        "The future is doing a backflip for you.",
        "The fates are knitting you a victory scarf.",
        "The horoscope says 'winning.'",
        "The tarot card was the Sun… and also a rainbow.",
        "The answer is written in golden ink.",
        "The universe is your hype squad.",
        "The magic is giving you a thumbs-up.",
        "The spirits are popping confetti.",
        "The tea kettle whistled 'YES!'",
        "The path is paved with high-fives.",
        "The stars aligned… and then threw a party.",
        "The oracle is already celebrating.",
        "The bones spelled 'LEGENDARY.'",
        "The future smells like fresh cookies.",
        "The universe whispered 'go for it, champ.'",
        "The prophecy is just a love letter to your success.",
        "The crystal ball is blasting victory music.",
        "The answer is glowing like a supernova.",
        "The cosmic jury ruled in your favor—unanimously.",
        "Yes, with extra sprinkles.",
        "The universe is handing you a trophy.",
        "The spirits are doing cartwheels.",
        "The tea leaves formed a smiley face.",
        "The runes say 'heckin’ right!'",
        "The pendulum swung to 'party time.'",
        "The oracle giggled with glee.",
        "The future is giving you a gold star.",
        "The stars spelled 'YAAAS.'",
        "The cosmic contract is signed in glitter.",
        "The answer is a resounding HELL YES.",
        "The universe is rolling out a red carpet.",
        "The magic is flexing for you.",
        "The spirits are chanting your name.",
        "The tea leaves spelled 'total victory.'",
        "The bones rattled 'you’re unstoppable.'",
        "The future is legally required to say yes.",
        "The oracle is wearing a 'Team You' shirt.",
        "The stars are throwing a parade in your honor.",
        "The cosmic scales tipped to 'legendary.'",
        "A unicorn stamped it 'APPROVED.'",
        "The stars twinkled 'you’ve got this.'",
        "The universe sent you a love letter.",
        "The magic is sprinkling luck on you.",
        "The spirits are baking you a success cake.",
        "The tea is sweet, like your future.",
        "The runes are doing a conga line.",
        "The pendulum is swinging to 'pure bliss.'",
        "The oracle is handing you a golden ticket.",
        "The future is a disco ball of possibilities.",
        "The cosmos are popping champagne.",
        "The answer is so yes, it’s sparkling.",
        "The universe is giving you a standing ovation.",
        "The magic just crowned you.",
        "The spirits are singing your praises.",
        "The tea leaves formed a trophy.",
        "The bones spelled 'ICONIC.'",
        "The future is a fireworks finale.",
        "The oracle is writing a ballad about you.",
        "The cosmic printer is out of ink… from printing W’s.",
        "The answer is wrapped in a bow.",
        "The universe is hugging you.",
        "The magic is blowing you kisses.",
        "The spirits left you a love note.",
        "The tea is honey-sweet, like your luck.",
        "The runes are giggling 'yes.'",
        "The pendulum is swaying to 'pure joy.'",
        "The oracle handed you a bouquet of yeses.",
        "The future is a puppy pile of happiness.",
        "The cosmic warranty is lifetime happiness.",
        "The answer is carved into Mount Yes.",
        "The universe is playing your theme song.",
        "The magic is giving you VIP access.",
        "The spirits are clinking glasses for you.",
        "The tea is steeped in greatness.",
        "The bones spelled 'GOAT.'",
        "The future is a highlight reel.",
        "The oracle is taking notes from you.",
        "The cosmic scales tipped to 'eternal win.'",
        "The stars are your personal cheer squad.",
        "The path is lined with rainbows.",
        "The universe is handing you a treasure map.",
        "The magic is packing your bags for success.",
        "The spirits are whispering 'go get it.'",
        "The tea leaves formed a compass pointing to 'yes.'",
        "The bones rattled 'adventure calls.'",
        "The future is a first-class ticket to joy.",
        "The oracle is holding the door open for you.",
        "The cosmic GPS says 'destination: happiness.'",
        "The answer is a golden 'onward!'",
        "The universe is your biggest fan.",
        "The magic is doing a happy dance.",
        "The spirits are giving you a thumbs-up.",
        "The tea leaves spelled 'you’re amazing.'",
        "The runes are shining bright.",
        "The pendulum is swinging to 'pure delight.'",
        "The oracle is handing you a crown.",
        "The future is a standing ovation.",
        "The stars are singing your praises.",
        "The cosmic contract is signed in stardust.",
        "The answer is a resounding 'YES, KING/QUEEN!'",
        "The universe is giving you a high-five.",
        "The magic is sprinkling fairy dust.",
        "The spirits are toasting to you.",
        "The tea is brewed with good vibes.",
        "The bones spelled 'CHAMPION.'",
        "The future is a love letter to you.",
        "The oracle is nodding enthusiastically.",
        "The cosmic scales say '100% awesome.'",
        "The stars are your personal hype team.",
        "The answer is a fireworks show of yes.",
        "The universe is handing you the mic.",
        "The magic is giving you a victory lap.",
        "The spirits are cheering loudly.",
        "The tea leaves formed a gold medal.",
        "The bones rattled 'unstoppable.'",
        "The future is a red-carpet moment.",
        "The oracle is writing your success story.",
        "The cosmic Wi-Fi is at full bars.",
        "The answer is a neon 'GO FOR IT.'",
        "The universe is your co-pilot.",
        "The magic is sending good vibes.",
        "The spirits are clapping for you.",
        "The tea leaves spelled 'dream big.'",
        "The runes are beaming with pride.",
        "The pendulum is swinging to 'absolute win.'",
        "The oracle is giving you a gold star.",
        "The future is a confetti cannon.",
        "The stars are shining just for you.",
        "The cosmic contract is sealed with joy.",
        "The answer is a symphony of yeses.",
        "The universe is your cheerleader.",
        "The magic is granting your wish.",
        "The spirits are doing a happy dance.",
        "The tea is steeped in success.",
        "The bones spelled 'YOU GOT THIS.'",
        "The future is a high-five from fate.",
        "The oracle is smiling knowingly.",
        "The cosmic scales say '100% blessed.'",
        "The stars are winking in agreement.",
        "The answer is a golden ticket.",
        "The universe is applauding you.",
        "The magic is on your side.",
        "The spirits are singing your praises.",
        "The tea leaves formed a heart.",
        "The bones rattled 'victory is yours.'",
        "The future is a love song.",
        "The oracle is handing you the keys.",
        "The cosmic GPS says 'success ahead.'",
        "The answer is a resounding 'YES, YES, YES!'",
        "The universe is your biggest supporter.",
        "The magic is whispering 'you’ve got this.'",
        "The spirits are giving you a standing ovation.",
        "The tea leaves spelled 'pure greatness.'",
        "The runes are glowing with joy.",
        "The pendulum is swinging to 'absolute yes.'",
        "The oracle is handing you a trophy.",
        "The future is a celebration.",
        "The stars are aligned in your favor.",
        "The cosmic contract is signed with love.",
        "The answer is a rainbow of yes.",
        "The universe is your personal coach.",
        "The magic is cheering you on.",
        "The spirits are throwing you a party.",
        "The tea is brewed with happiness.",
        "The bones spelled 'DESTINED FOR GREATNESS.'",
        "The future is a hug from destiny.",
        "The oracle is nodding in approval.",
        "The cosmic scales say 'overflowing with yes.'",
        "The stars are your lucky charms.",
        "The answer is a megaphone shout of YES.",
        "The universe is your hype train.",
        "The magic is sprinkling stardust.",
        "The spirits are giving you a thumbs-up.",
        "The tea leaves formed a trophy.",
        "The bones rattled 'you’re a star.'",
        "The future is a victory parade.",
        "The oracle is writing your name in the stars.",
        "The cosmic Wi-Fi is at full strength.",
        "The answer is a banner of triumph.",
        "The universe is your fairy godparent.",
        "The magic is sending you good luck.",
        "The spirits are toasting to your success.",
        "The tea leaves spelled 'legend in the making.'",
        "The runes are dancing with joy.",
        "The pendulum is swinging to 'pure magic.'",
        "The oracle is handing you a golden key.",
        "The future is a dream come true.",
        "The stars are your personal guardians.",
        "The cosmic contract is eternal happiness."
      ],
    negative: [
        "The stars say 'lol no.'",
        "Outlook: moldy.",
        "The spirits rolled their eyes.",
        "The tea leaves spelled 'nope.'",
        "The cosmic Wi-Fi disconnected.",
        "The oracle sighed deeply.",
        "The runes crumbled to dust.",
        "The pendulum fell off.",
        "The crystal ball cracked.",
        "A cursed raccoon says no.",
        "The future smells like regret.",
        "The fates cackled ominously.",
        "The horoscope just says 'yikes.'",
        "The tarot card was the Tower… upside-down.",
        "The answer is buried in cursed soil.",
        "The universe filed a restraining order.",
        "The magic backfired. Try again never.",
        "The spirits flipped the table.",
        "The tea kettle screamed 'ABORT.'",
        "The apocalypse is more likely.",
        "The stars wrote 'abandon hope.'",
        "The oracle fainted in horror.",
        "The bones spelled 'RUN.'",
        "The future is a dumpster fire.",
        "The universe hissed 'don’t.'",
        "The prophecy was redacted for your safety.",
        "The crystal ball showed a void.",
        "The answer is lost in the Shadow Realm.",
        "The cosmic jury sentenced you to 'no.'",
        "Sure, if you enjoy disappointment.",
        "Technically possible, but also tragic.",
        "The universe said 'hard pass.'",
        "The spirits are roasting you.",
        "The tea went cold out of spite.",
        "The runes say 'delulu.'",
        "The pendulum swung to 'ew.'",
        "The oracle gagged.",
        "The future is cringing.",
        "The stars said 'bless your heart.'",
        "The answer is forbidden.",
        "The universe is side-eyeing you.",
        "The magic malfunctioned… on purpose.",
        "The spirits are whispering 'bad idea.'",
        "The tea leaves formed a frowny face.",
        "The bones rattled 'no way.'",
        "The future is legally obligated to say no.",
        "The oracle coughed uncomfortably.",
        "The stars are judging you silently.",
        "The cosmic contract was voided.",
        "The path is blocked by sorrow.",
        "The answer is six feet under.",
        "The universe closed that door forever.",
        "The magic is out… of mercy.",
        "The spirits are mourning your choices.",
        "The tea is bitter, like the truth.",
        "The runes are in mourning.",
        "The pendulum is stuck on 'despair.'",
        "The oracle wore black to this reading.",
        "The future is a closed casket.",
         "A demon said 'lmao no.'",
        "The stars spelled 'ERROR 404.'",
        "The universe yeeted your hopes away.",
        "The magic cursed you for asking.",
        "The spirits threw tomatoes at you.",
        "The tea leaves spelled 'oof.'",
        "The bones spelled 'F.'",
        "The future is a clown car crash.",
        "The oracle quit mid-sentence.",
        "The cosmic printer is out of ink… and hope.",
            "The door is sealed with ancient regret.",
        "The answer is locked in a cursed vault.",
        "The universe marked it 'return to sender.'",
        "The magic faded to a whimper.",
        "The spirits wrote 'nice try.'",
        "The tea is poisoned (metaphorically).",
        "The runes are on strike.",
        "The pendulum snapped in half.",
        "The oracle handed you a consolation potato.",
        "The future is a cancelled Netflix show.",
        "The void stared back… and laughed.",
        "The answer is lost in the backrooms.",
        "The universe sighed in secondhand embarrassment.",
        "The magic is on life support.",
        "The spirits filed a complaint.",
        "The tea is steeped in existential angst.",
        "The bones spelled 'why bother?'",
        "The future is a void screaming into another void.",
        "The oracle is on a stress leave.",
        "The cosmic warranty expired.",
            "The stars wrote 'this ends in tears.'",
        "The universe is charging you a stupid tax.",
        "The magic is out… like your chances.",
        "The spirits are placing bets against you.",
        "The tea is as bitter as your fate.",
        "The bones spelled 'doomed.'",
        "The future is a trainwreck in slow motion.",
        "The oracle lit a candle for your hopes.",
        "The cosmic scales tipped… into the abyss.",
        "The answer is no, with a side of despair.",],
    neutral: [
        "The universe shrugs.",
        "Cloudy with a chance of maybe.",
        "Flip a phantom coin.",
        "The answer is... adequately ambiguous.",
        "Ask again, but whisper it this time.",
        "The odds are as even as they’ll ever be.",
        "Indecision is the wisest choice here.",
        "The winds of fate are breezy, not gusty.",
        "Somewhere, a cat is half in and half out of a box.",
        "The tea leaves say 'meh.'",
        "The stars are taking a coffee break.",
        "A mystery wrapped in a shrug.",
        "The cosmic dice landed on the edge.",
        "The answer is currently out for lunch.",
        "The oracle yawned and said, 'Could go either way.'",
        "The universe is buffering.",
        "The magic is malfunctioning politely.",
        "The answer is neither here nor there.",
        "The spirits are on mute.",
        "The future is in beta testing.",
        "The runes spell 'kinda.'",
        "The crystal ball is fogged with neutrality.",
        "The cosmic scales are perfectly unbalanced.",
        "The answer is a soft maybe.",
        "The universe is noncommittal today.",
        "The pendulum swung sideways.",
        "The fortune cookie was blank.",
        "The tarot card was a blur.",
        "The answer is lost in translation.",
        "The divination Wi-Fi is weak.",
        "The prophecy is under review.",
        "The horoscope says '¯\_(ツ)_/¯.'",
        "The answer is a lukewarm 'perhaps.'",
        "The cosmic jury is hung.",
        "The astral plane is under construction.",
        "The answer is a gentle 'who knows?'",
        "The fates are on a smoke break.",
        "The mystic energies are at 50%.",
        "The answer is a non-answer.",
        "The universe is playing hard to get.",
        "The ouija board glided to 'idk.'",
        "The answer is a diplomatic 'possibly.'",
        "The stars are filing paperwork.",
        "The cosmic coin is spinning… forever.",
        "The answer is a cautious 'could be.'",
        "The spirits are consulting a lawyer.",
        "The future is in grayscale.",
        "The oracle is using incognito mode.",
        "The answer is a firm 'maybe-ish.'",
        "The universe is keeping its options open.",
        "The magic is on standby.",
        "The answer is a tentative 'sorta.'",
        "The cosmic reception is fuzzy.",
        "The tea leaves formed a question mark.",
        "The answer is a polite 'ask later.'",
        "The fates are in a meeting.",
        "The prediction is stuck in traffic.",
        "The answer is a neutral 'eh.'",
        "The stars are updating their software.",
        "The crystal ball says 'define your terms.'",
        "The answer is a vague 'perchance.'",
        "The universe is pondering.",
        "The magic is out of office.",
        "The answer is a soft 'if you say so.'",
        "The spirits are multitasking.",
        "The future is loading… slowly.",
        "The oracle is reading the fine print.",
        "The answer is a diplomatic 'time will tell.'",
        "The cosmic dice rolled off the table.",
        "The tea is steeped in uncertainty.",
        "The answer is a careful 'let’s see.'",
        "The fates are negotiating.",
        "The prediction is pending approval.",
        "The answer is a mild 'who’s to say?'",
        "The universe is reserving judgment.",
        "The magic is calibrating.",
        "The answer is a hesitant 'suppose so.'",
        "The spirits are on a lunch break.",
        "The future is in draft mode.",
        "The oracle is consulting Yelp.",
        "The answer is a measured 'it depends.'",
        "The cosmic scales are napping.",
        "The tea leaves are unimpressed.",
        "The answer is a nonchalant 'whatever.'",
        "The fates are in a group chat.",
        "The prediction is on hold.",
        "The answer is a patient 'we’ll see.'",
        "The universe is typing… then deleting.",
        "The magic is buffering.",
        "The answer is a lazy 'sure, why not?'",
        "The spirits are scrolling TikTok.",
        "The future is set to 'shuffle.'",
        "The oracle is out of spoons.",
        "The answer is a sleepy 'maybe tomorrow.'",
        "The cosmic dice are shy.",
        "The tea is lukewarm and so is the answer.",
        "The answer is a breezy 'could happen.'",
        "The fates are vibing.",
        "The prediction is TBD.",
        "The universe whispers, 'I’ll get back to you.'",
    ]
}

export default [ ...answers.positive, ...answers.negative, ...answers.neutral ]